### ISSUE TITLE
Stop hiding buffs for enemies

### ISSUE THREAD

**Issue by funkydude** [Phanx/oUF_Phanx#10]
When it comes to enemies, I don't want to hold SHIFT to see what beneficial buffs it has.

Maybe you did this for PvP, in which case you should stop hiding them for NPCs where gaining a buff means you need to take some form of action, such as dispelling, or using a cooldown.

**Comment by funkydude** [comment]
I'm also noticing a lot of the time even holding shift won't reveal everything. For example, holding shift on an ally would not show me this debuff: http://www.wowhead.com/spell=204813/blindfold

Infact holding shift didn't show me anything on them.

**Comment by Phanx** [comment]
Dispellable buffs on enemies (whether they're players or NPCs) should trigger the dispel highlight. If you're not seeing that, more information (which buff or debuff, which class and spec) would be useful.

Other than that, I agree that there's not really any reason to hide buffs on NPCs, but I've also never noticed their lack either. Anything important is either dispellable (see above) or my boss mods tell me about it. Showing them is probably not a big deal, though, since NPCs are unlikely to have a ton of buffs. I'll go ahead and show anything with a duration of less than an hour (should rule out "aura" type buffs that are always on and you can't do anything about).

I'll look into the shift toggle. Keep in mind it's ignored during combat. Also, there's a limit on how many aura icons are shown, based on your frame width setting. I guess I can add another row of icons. Are there any specific types of buffs you're mainly concerned with? The only reason the shift toggle exists in the first place is because I wanted to be able to see what mounts people were using.

**Comment by funkydude** [comment]
>I'll go ahead and show anything with a duration of less than an hour (should rule out "aura" type buffs that are always on and you can't do anything about).

Awesome.

>Keep in mind it's ignored during combat.

This was during combat :(
As a boss mod author, seeing a boss debuff on someone makes me think "oh I better look at the log for that" when I don't see one, I sometimes don't even bother and assume it's yet another hidden debuff (a common issue)

>I guess I can add another row of icons.

That would be cool, but in this case, it wasn't a problem of too many icons, I don't think. I'm not sure, since I couldn't see any buffs/debuffs (in combat). There should hopefully be less of a concern with the buff removals in this patch.

I can't really say specific debuffs, I guess I'd like shift to be a "show everything" if that's possible, the second row would help with that.

**Comment by Phanx** [comment]
> As a boss mod author, seeing a boss debuff on someone ...

Anything flagged as a boss aura should already be shown on everyone (players and NPCs) unless it's specifically blacklisted. (Actually, looking at the code now, boss auras aren't whitelisted on party/focus/TOT frames; I'll fix that now.)

**Comment by funkydude** [comment]
Not sure if this was the intention heh
![debuffs](https://cloud.githubusercontent.com/assets/16833/17822363/a89008fe-664e-11e6-8f6e-1b80ec8e9a60.png)

**Comment by Phanx** [comment]
Not the intention, just the result of drycoding while the issue was on my mind. I should have time to test it and fix the logic this weekend.
